name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
    - cron: '0 10 * * *' # run at 10 AM UTC

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: Install rust stable
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        components: rustfmt, clippy
        override: true

    - name: Fix ~/.cargo directory permissions
      run: |
        # Need to chown ~/.cargo or else the "Cache cargo registry" step will fail.
        # See https://github.com/actions/cache/issues/133.
        sudo chown -R $(whoami):$(id -ng) ~/.cargo/

    - name: Cache cargo registry
      uses: actions/cache@v1
      with:
        path: ~/.cargo/registry
        key: ${{ runner.os }}-cargo-test-registry-${{ hashFiles('**/Cargo.toml') }}

    - name: Cache cargo build
      uses: actions/cache@v1
      with:
        path: target
        key: ${{ runner.os }}-cargo-test-build-${{ hashFiles('**/Cargo.toml') }}

    - name: Lint with rustfmt
      if: always()
      uses: actions-rs/cargo@v1
      with:
        command: fmt
        args: -- --check

    - name: Lint with clippy
      if: always()
      uses: actions-rs/cargo@v1
      with:
        command: clippy
        args: --all-targets -- -D warnings

    - name: Run unit tests
      if: always()
      uses: actions-rs/cargo@v1
      with:
        command: test
        args: --lib

    - name: Run doc tests
      if: always()
      uses: actions-rs/cargo@v1
      with:
        command: test
        args: --doc

    - name: Run runtime tests
      if: always()
      uses: actions-rs/cargo@v1
      with:
        command: test
        args: --test runtime

    - name: Run codegen tests
      if: always()
      uses: actions-rs/cargo@v1
      with:
        command: test
        args: --test codegen
